export const GETALLPROJECT_REQUEST = "GETALLPROJECT_REQUEST";
export const GETALLPROJECT_SUCCESS = "GETALLPROJECT_SUCCESS";
export const GETALLPROJECT_ERROR = "GETALLPROJECT_ERROR";

export const CREATEPROJECT = "CREATEPROJECT";

export const DELETEPROJECT = "DELETEPROJECT";

export const EDITPROJECT = "EDITPROJECT"

export const SEARCHPROJECT = "SEARCHPROJECT"

export const REMOVE_USERPROJECT = 'REMOVE_USERPROJECT'

export const ASSIGN_USERPROJECT = 'ASSIGN_USERPROJECT'