export const GETALLPROJECT_REQUEST = "GETALLPROJECT_REQUEST";
export const GETALLPROJECT_SUCCESS = "GETALLPROJECT_SUCCESS";
export const GETALLPROJECT_ERROR = "GETALLPROJECT_ERROR";

export const GETPROJECTDETAIL_REQUEST = "GETPROJECTDETAIL_REQUEST";
export const GETPROJECTDETAIL_SUCCESS = "GETPROJECTDETAIL_SUCCESS";
export const GETPROJECTDETAIL_ERROR = "GETPROJECTDETAIL_ERROR";

export const CREATEPROJECT = "CREATEPROJECT";

export const DELETEPROJECT = "DELETEPROJECT";

export const EDITPROJECT = "EDITPROJECT"

export const REMOVE_USERPROJECT = 'REMOVE_USERPROJECT'

export const ASSIGN_USERPROJECT = 'ASSIGN_USERPROJECT'