export const GETALLSTATUS = "GETALLSTATUS";

export const UPDATESTATUS = "UPDATESTATUS";

export const GETALLPRIORITY = "GETALLPRIORITY";

export const UPDATEPRIORITY = "UPDATEPRIORITY";

export const UPDATE_TIMETRACKING = "UPDATE_TIMETRACKING";

export const GETALLTASKTYPE = "GETALLTASKTYPE";

export const ASSIGN_USERTASK = "ASSIGN_USERTASK";

export const REMOVE_USERTASK = "REMOVE_USERTASK";

export const CREATETASK = "CREATETASK";

export const GETTASKDETAIL = "GETTASKDETAIL";

export const UPDATETASK = "UPDATETASK";

export const REMOVETASK = 'REMOVETASK'
