export const LISTUSER_REQUEST = "LISTUSER_REQUEST";
export const LISTUSER_SUCCESS = "LISTUSER_SUCCESS";
export const LISTUSER_ERROR = "LISTUSER_ERROR";

export const USER_PROJECTID = 'USER_PROJECTID';

export const SEARCH_USER = "SEARCH_USER";

export const DELETE_USER = "DELETE_USER";

export const EDIT_USER = 'EDIT_USER'
